version: 2
updates:
  # Go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Etc/UTC"
    assignees:
      - "sukhera"
    reviewers:
      - "sukhera"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "automated"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"
    target-branch: "main"
    # Group minor and patch updates
    groups:
      go-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Node.js dependencies for React frontend
  - package-ecosystem: "npm"
    directory: "/web/react-status-page"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Etc/UTC"
    assignees:
      - "sukhera"
    reviewers:
      - "sukhera"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "nodejs"
      - "frontend"
      - "automated"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"
    target-branch: "main"
    # Ignore specific packages that require manual updates
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
    # Group development dependencies
    groups:
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "@vitejs/*"
          - "eslint*"
          - "vite"
          - "tailwindcss"
          - "postcss"
          - "autoprefixer"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "*"
        update-types:
          - "patch"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/configs/docker"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "Etc/UTC"
    assignees:
      - "sukhera"
    reviewers:
      - "sukhera"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "infrastructure"
      - "automated"
    open-pull-requests-limit: 3
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"
    target-branch: "main"

  # Docker for React frontend
  - package-ecosystem: "docker"
    directory: "/web/react-status-page"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "Etc/UTC"
    assignees:
      - "sukhera"
    reviewers:
      - "sukhera"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "frontend"
      - "automated"
    open-pull-requests-limit: 2
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"
    target-branch: "main"

  # GitHub Actions Configuration
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
      timezone: "Etc/UTC"
    assignees:
      - "sukhera"
    reviewers:
      - "sukhera"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
      - "automated"
    open-pull-requests-limit: 3
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"
    target-branch: "main"
    # Group GitHub Actions updates
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
