# Security-focused Dependabot Configuration
# This configuration only creates PRs for security vulnerabilities and critical updates

version: 2
updates:
  # Go dependencies - Security only
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Etc/UTC"
    assignees:
      - "sukhera"
    reviewers:
      - "sukhera"
    commit-message:
      prefix: "security(deps)"
      prefix-development: "security(deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
      - "go"
      - "high-priority"
    open-pull-requests-limit: 3
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"
    target-branch: "main"
    # CRITICAL: Only allow security updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
    # Explicitly enable security updates
    allow:
      - dependency-type: "all"
        update-type: "security"

  # Node.js dependencies - Security only
  - package-ecosystem: "npm"
    directory: "/web/react-status-page"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Etc/UTC"
    assignees:
      - "sukhera"
    reviewers:
      - "sukhera"
    commit-message:
      prefix: "security(deps)"
      prefix-development: "security(deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
      - "nodejs"
      - "frontend"
      - "high-priority"
    open-pull-requests-limit: 3
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"
    target-branch: "main"
    # CRITICAL: Only allow security updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
    # Explicitly enable security updates
    allow:
      - dependency-type: "all"
        update-type: "security"

  # Docker base images - Security only
  - package-ecosystem: "docker"
    directory: "/configs/docker"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "Etc/UTC"
    assignees:
      - "sukhera"
    reviewers:
      - "sukhera"
    commit-message:
      prefix: "security(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
      - "docker"
      - "infrastructure"
      - "high-priority"
    open-pull-requests-limit: 2
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"
    target-branch: "main"
    # CRITICAL: Only allow security updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
    # Explicitly enable security updates
    allow:
      - dependency-type: "all"
        update-type: "security"

  # Frontend Docker - Security only
  - package-ecosystem: "docker"
    directory: "/web/react-status-page"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:30"
      timezone: "Etc/UTC"
    assignees:
      - "sukhera"
    reviewers:
      - "sukhera"
    commit-message:
      prefix: "security(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
      - "docker"
      - "frontend"
      - "high-priority"
    open-pull-requests-limit: 2
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"
    target-branch: "main"
    # CRITICAL: Only allow security updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
    # Explicitly enable security updates
    allow:
      - dependency-type: "all"
        update-type: "security"

  # GitHub Actions - Security only
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
      timezone: "Etc/UTC"
    assignees:
      - "sukhera"
    reviewers:
      - "sukhera"
    commit-message:
      prefix: "security(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
      - "github-actions"
      - "ci"
      - "high-priority"
    open-pull-requests-limit: 2
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"
    target-branch: "main"
    # CRITICAL: Only allow security updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
    # Explicitly enable security updates
    allow:
      - dependency-type: "all"
        update-type: "security"