with-expecter: true
packages:
  github.com/sukhera/uptime-monitor/internal/database:
    config:
      dir: "mocks"
      mockname: "MockDatabaseInterface"
      filename: "MockDatabaseInterface.go"
    interfaces:
      Interface: