with-expecter: true
packages:
  github.com/sukhera/uptime-monitor/internal/database:
    config:
      dir: "mocks"
      mockname: "Mock{{.InterfaceName}}"
      filename: "{{.MockName}}.go"
    interfaces:
      DatabaseInterface: