version: '3.9'

services:
  mongo:
    image: mongo:6.0
    container_name: status-mongo-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-devpassword}
      MONGO_INITDB_DATABASE: status_page
    volumes:
      - mongo_dev_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ismaster')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - status-network

  status-checker:
    build:
      context: .
      dockerfile: configs/docker/Dockerfile.api.dev
    container_name: status-checker-dev
    volumes:
      - .:/app
      - /app/tmp
    environment:
      MONGO_URI: ${MONGO_URI:-mongodb://mongo:27017/status_page}
      GO_ENV: development
      HOT_RELOAD: ${HOT_RELOAD:-true}
      RETENTION_DAYS: ${RETENTION_DAYS:-30}
    command: air -c configs/dev/air.toml
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - status-network

  api:
    build:
      context: .
      dockerfile: configs/docker/Dockerfile.api.dev
    container_name: status-api-dev
    volumes:
      - .:/app
      - /app/tmp
    environment:
      MONGO_URI: ${MONGO_URI:-mongodb://mongo:27017/status_page}
      PORT: ${PORT:-8080}
      GO_ENV: development
      HOT_RELOAD: ${HOT_RELOAD:-true}
      JWT_SECRET: ${JWT_SECRET:-dev_jwt_secret_not_for_production}
    command: air -c configs/dev/air.toml
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - status-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    container_name: status-web-dev
    volumes:
      - ./web/react-status-page:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      VITE_API_URL: ${VITE_API_URL:-http://localhost:8080/api}
    ports:
      - "5173:5173"
    networks:
      - status-network

networks:
  status-network:
    driver: bridge

volumes:
  mongo_dev_data:
    driver: local