blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/sukhera/uptime-monitor/blob/main/README.md
    about: Please check our documentation before opening an issue
  - name: 💬 GitHub Discussions
    url: https://github.com/sukhera/uptime-monitor/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Vulnerability
    url: https://github.com/sukhera/uptime-monitor/security/advisories/new
    about: Please report security vulnerabilities through GitHub's security advisory feature